### ISSUE TITLE
Setup Account Information DB Table

### ISSUE THREAD

**Issue by burchcATWIT** [burchcATWIT/password_manager#14]

**Comment by hogana3atwit** [comment]
{"_id":{"$oid":"623bc0e9fd3ebb5c9b150092"},"accountUsername":"Alexane_Schneider","siteUsername":"Alexane_Schneider_Carroll83@hotmail.com","sitePassword":"bvmfRyrZb2OllV3","OtherNotes":"We need to reboot the digital HTTP interface!","siteName":"scholarly-entirety.com"}

Example test table entry showing Device and Account Management information
